const CONFIG = {
  WEB_APP_URL:
    "https://script.google.com/macros/s/AKfycbzaBoGR30gvRER7bFR_PWJShtYsqU-qGUrZwFTwu5OcvImBwyR05Pq2xdtaq1be8Rxk/exec",
  DRIVE_FOLDER_ID: "1CMwq8DLgaeY6DOub6i6Y_A00P_-JBgrp",
  SHEET_NAME: "Expenses",
  MAX_UPLOAD_SIZE_MB: 20,
  MAX_UPLOAD_SIZE_BYTES: 20 * 1024 * 1024,
  ALLOWED_FILE_TYPES: [
    "jpg",
    "jpeg",
    "png",
    "pdf",
    "doc",
    "docx",
    "xls",
    "xlsx",
    "zip",
  ],
  ALLOWED_MIME_TYPES: [
    "image/jpeg",
    "image/png",
    "application/pdf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/zip",
  ],
  APP_NAME: "Expense Management System",
  ORG_NAME: "Yogii",
  DASHBOARD_REFRESH_INTERVAL: 30000,
  ROWS_PER_PAGE_OPTIONS: [10, 25, 50, 100],
  DEFAULT_ROWS_PER_PAGE: 10,
  AUTH: {
    USERNAME: "yogii",
    PASSWORD: "1502",
    USERS: [
      { USERNAME: "yogii", PASSWORD: "1502", NAME: "Yogii" },
      { USERNAME: "bt", PASSWORD: "123", NAME: "Balaji Thiru" },
      { USERNAME: "bv", PASSWORD: "123", NAME: "Balaji Varadhan" }
    ],
    SESSION_KEY: "ems_session",
  },
  CATEGORIES: [
    "Travel",
    "Components",
    "Office",
    "Accommodation",
    "Food",
    "Fuel",
    "Maintenance",
    "Miscellaneous",
  ],
  FOUNDERS: ["Balaji Thiru", "Balaji Varadhan"],
  EMPLOYEES: [
    "Yogesh",
    "Logesh",
    "Mogan",
    "Lalith",

    "Devi",
    "Ashmitha",
    "Rahul",
    "Aswimini",
    "Office",
  ],
  PAYMENT_STATUSES: ["Pending", "Paid"],
  SORT_OPTIONS: [
    { value: "date_desc", label: "Latest" },
    { value: "date_asc", label: "Oldest" },
    { value: "amount_desc", label: "Highest Amount" },
    { value: "amount_asc", label: "Lowest Amount" },
    { value: "founder_asc", label: "Founder" },
    { value: "employee_asc", label: "Employee" },
    { value: "status_asc", label: "Status" },
  ],
  CHART_COLORS: {
    primary: "#1a56db",
    secondary: "#3f83f8",
    success: "#0e9f6e",
    warning: "#c27803",
    danger: "#e02424",
    info: "#0694a2",
    purple: "#7e3af2",
    pink: "#d61f69",
    palette: [
      "#1a56db",
      "#0e9f6e",
      "#c27803",
      "#e02424",
      "#7e3af2",
      "#d61f69",
      "#0694a2",
      "#f05252",
    ],
  },
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = CONFIG;
}
